version: '3.3'
services:
  mysql_8:
    image: "mysql:8"
    ports:
      - "3306:3306"
    networks:
      - backend
    volumes:
      - "mysql_8_db_data:/var/lib/mysql"
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max_connections=1000 --general_log=off --skip-log-bin
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  redis_queue:
    image: "redis:5"
    ports:
      - "6381:6379"
    networks:
      - backend
    command: --save "" --appendonly no
    restart: always
  mongodb_library_tongjiuniversity:
    image: "mongo:3"
    networks:
      - backend
    ports:
      - "27017:27017"
    volumes:
      - "mongodb_library_tongjiuniversity:/data/db"
      - "E:\\Projects\\rho.one\\vendor\\rhoone\\rhoone-library-huiwen-tongjiuniversity\\mongodb\\config\\tongjiuniversity.js:/docker-entrypoint-initdb.d/tongjiuniversity.js:ro"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: tongjiuniversity
    command: --ipv6
    restart: always
  elasticsearch:
    image: "vistart/elasticsearch:6.6.1"
    networks:
      - backend
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "elasticsearch_6_data:/usr/share/elasticsearch/data"
    restart: always
  kibana:
    image: "kibana:6.5.4"
    networks:
      - backend
    ports:
      - "5601:5601"
    restart: always
  rabbitmq:
    image: "rabbitmq:management"
    networks:
      - backend
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
  php_apache:
    image: "vistart/php:7.2-apache"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "composer_cache:/root/.composer/"
      - "G:\\Volumes\\vistart\\php\\www\\html:/var/www/html"
      - "E:\\Projects\\rho.one:/var/www/rho.one"
      - "E:\\Projects\\rho.one\\server.config\\rho.one.conf:/etc/apache2/sites-available/rho.one.conf"
    networks:
      - frontend
      - backend
    restart: always

networks:
  frontend:
  backend:

volumes:
  composer_cache:
  mysql_8_db_data:
  elasticsearch_6_data:
  mongodb_library_tongjiuniversity: